ISUCON13_MYSQL_DIALCONFIG_NET="tcp"
ISUCON13_MYSQL_DIALCONFIG_ADDRESS="192.168.0.12"
ISUCON13_MYSQL_DIALCONFIG_PORT="5432"
ISUCON13_MYSQL_DIALCONFIG_USER="isucon"
ISUCON13_MYSQL_DIALCONFIG_DATABASE="isupipe"
ISUCON13_MYSQL_DIALCONFIG_PARSETIME="true"
ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="54.95.27.63"
ISUCON13_POWERDNS_DISABLED="false"

PGPASSWORD=isucon
DB_USER=isucon
DB_PASS=isucon
DB_HOSTNAME=192.168.0.12
DB_PORT=5432
DB_DATABASE=isupipe

OTEL_SDK_DISABLED=false
OTEL_SERVICE_NAME=isupipe
OTEL_EXPORTER_OTLP_ENDPOINT=http://monitoring:4318
PYROSCOPE_SERVER_ADDRESS=http://monitoring:4040
